// <auto-generated />
using System;
using Insurance.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Insurance.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("Insurance.Api.Models.ProductTypeSurcharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SurchargeRate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductTypeSurcharges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductTypeId = 21,
                            SurchargeRate = 10m,
                            Version = new Guid("869040e7-3f1a-441c-b72b-d9f4c14f1ba6")
                        },
                        new
                        {
                            Id = 2,
                            ProductTypeId = 32,
                            SurchargeRate = 20m,
                            Version = new Guid("26d5a2f3-c354-493e-af50-974f50908e0c")
                        },
                        new
                        {
                            Id = 3,
                            ProductTypeId = 12,
                            SurchargeRate = 30m,
                            Version = new Guid("93acae4e-e962-4ba7-a168-e9b8c09d9ea0")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
